
const actionTypes ={
    GET_HOME :'GET_HOME',
    SET_CUR_SONG_ID: 'SET_CUR_SONG_ID',
    SET_CUR_SONG_DATA: 'SET_CUR_SONG_DATA',
    SET_CUR_ALBUM_ID: 'SET_CUR_ALBUM_ID',
    SET_RECENT :'SET_RECENT',
    CURRENT_WIDTH : 'CURRENT_WIDTH',
    
    // Music
    SET_PLAYING:'SET_PLAYING',
    SET_ALBUM :'SET_ALBUM',
    ADD_PLAYLIST:'ADD_PLAYLIST',
    SEARCH : 'SEARCH'
} 

export default actionTypes;